In [5]:
import pandas as pd
import seaborn as sb
from pylab import rcParams
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
rcParams['figure.figsize']=5,4
sb.set_style('whitegrid')

In [7]:
df=pd.read_csv("C:\\Users\\SAGAR\\Documents\\ashwini\\pandas\\linear_regression\\MELBOURNE_HOUSE_PRICES_LESS.csv")
df

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Postcode,Regionname,Propertycount,Distance,CouncilArea
0,Abbotsford,49 Lithgow St,3,h,1490000.0,S,Jellis,01-04-2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
1,Abbotsford,59A Turner St,3,h,1490000.0,S,Marshall,01-04-2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
2,Abbotsford,119B Yarra St,3,h,1420000.0,S,Nelson,01-04-2017,3067,Northern Metropolitan,4019,3.0,Yarra City Council
3,Aberfeldie,68 Vida St,3,h,1515000.0,S,Barry,01-04-2017,3040,Western Metropolitan,1543,7.5,Moonee Valley City Council
4,Airport West,92 Clydesdale Rd,2,h,670000.0,S,Nelson,01-04-2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
5,Airport West,4/32 Earl St,2,t,530000.0,S,Jellis,01-04-2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
6,Airport West,3/74 Hawker St,2,u,540000.0,S,Barry,01-04-2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
7,Airport West,1/26 Highridge Cr,3,h,715000.0,SP,Nelson,01-04-2017,3042,Western Metropolitan,3464,10.4,Moonee Valley City Council
8,Albanvale,1 Jackson Cct,6,h,NaN,PI,hockingstuart,01-04-2017,3021,Western Metropolitan,1899,14.0,Brimbank City Council
9,Albert Park,18 Mills St,3,h,1925000.0,S,Cayzer,01-04-2017,3206,Southern Metropolitan,3280,3.0,Port Phillip City Council
10,Albion,3/15 Drummartin St,3,u,515000.0,S,Douglas,01-04-2017,3020,Western Metropolitan,2185,10.5,Brimbank City Council
11,Albion,3A Kororoit St,4,h,717000.0,S,Bells,01-04-2017,3020,Western Metropolitan,2185,10.5,Brimbank City Council
12,Alphington,55 Fulham Rd,2,h,1675000.0,S,Miles,01-04-2017,3078,Northern Metropolitan,2211,5.7,Darebin City Council
13,Alphington,41 Toolangi Rd,4,h,2008000.0,S,Jellis,01-04-2017,3078,Northern Metropolitan,2211,5.7,Darebin City Council
14,Altona,9 Delmont Av,2,h,860000.0,SP,Barlow,01-04-2017,3018,Western Metropolitan,5301,11.0,Hobsons Bay City Council
15,Altona Meadows,57 Tatman Dr,4,h,NaN,SN,Barry,01-04-2017,3028,Western Metropolitan,7630,15.5,Hobsons Bay City Council
16,Altona North,14 Seventh Av,3,h,720000.0,S,Hunter,01-04-2017,3025,Western Metropolitan,5132,9.4,Hobsons Bay City Council
17,Armadale,2/23 Ashleigh Rd,2,u,836000.0,S,Jellis,01-04-2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
18,Armadale,6A Auburn Gr,2,h,2110000.0,S,Jellis,01-04-2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
19,Armadale,746 High St,3,h,1386000.0,S,Marshall,01-04-2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
20,Armadale,14/25 Kooyong Rd,2,u,580000.0,VB,hockingstuart,01-04-2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
21,Armadale,6/38 Wattletree Rd,1,u,355000.0,S,hockingstuart,01-04-2017,3143,Southern Metropolitan,4836,6.3,Stonnington City Council
22,Ascot Vale,8 The Grove,3,h,1123100.0,S,Ray,01-04-2017,3032,Western Metropolitan,6567,4.3,Moonee Valley City Council
23,Ashburton,1/48 Karnak Rd,3,u,1270000.0,S,Fletchers,01-04-2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
24,Ashburton,1 Pitt St,4,h,NaN,S,Jellis,01-04-2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
25,Ashburton,61A Victory Bvd,3,t,1610000.0,S,Jellis,01-04-2017,3147,Southern Metropolitan,3052,10.2,Boroondara City Council
26,Ashwood,43 Douglas St,4,h,1435000.0,S,Ray,01-04-2017,3147,Southern Metropolitan,2894,10.2,Monash City Council
27,Aspendale,4 Jirrah Ct,4,h,1431000.0,S,hockingstuart,01-04-2017,3195,South-Eastern Metropolitan,2824,21.5,Kingston City Council
28,Aspendale Gardens,8 Mangrove Ct,4,h,996000.0,S,Ray,01-04-2017,3195,South-Eastern Metropolitan,2243,21.5,Kingston City Council
29,Attwood,46 Threadneedle St,4,h,NaN,SN,Barry,01-04-2017,3049,Northern Metropolitan,1130,16.5,Hume City Council
...,...,...,...,...,...,...,...,...,...,...,...,...,...
62993,Windsor,68 Hornby St,2,h,1000000.0,VB,Beller,30-12-2017,3181,Southern Metropolitan,4380,4.6,Port Phillip City Council
62994,Wollert,66 Fulham Wy,3,h,640000.0,S,HAR,30-12-2017,3750,Northern Metropolitan,2940,25.5,Whittlesea City Council
62995,Wollert,11 Tindales Rd,4,h,520600.0,S,Stockdale,30-12-2017,3750,Northern Metropolitan,2940,25.5,Whittlesea City Council
62996,Wonga Park,16 Fulford Rd,3,h,NaN,PI,Jellis,30-12-2017,3115,Eastern Victoria,1328,25.2,Manningham City Council
62997,Wyndham Vale,5 Chatswood Pl,3,h,410000.0,S,hockingstuart,30-12-2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
62998,Wyndham Vale,21 Mermaid Cr,3,h,400000.0,SP,Barry,30-12-2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
62999,Wyndham Vale,20 Olive Wy,5,h,NaN,VB,Greg,30-12-2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63000,Wyndham Vale,8 Opala Ct,3,h,416000.0,S,Sweeney,30-12-2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63001,Wyndham Vale,15 Yaltara Dr,3,h,NaN,S,hockingstuart,30-12-2017,3024,Western Metropolitan,5262,27.2,Wyndham City Council
63002,Yallambie,7/6 Borlase St,3,t,745000.0,S,Buckingham,30-12-2017,3085,Northern Metropolitan,1369,12.7,Banyule City Council
63003,Yallambie,8/6 Borlase St,3,t,655000.0,S,Buckingham,30-12-2017,3085,Northern Metropolitan,1369,12.7,Banyule City Council
63004,Yarraville,9 Alice St,2,h,870000.0,SP,Jas,30-12-2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63005,Yarraville,4/119 Gamon St,2,u,495000.0,SP,Village,30-12-2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63006,Yarraville,26 Grace St,3,h,1000000.0,SP,Jas,30-12-2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63007,Yarraville,2/13 Stephen St,2,u,410000.0,SP,Sweeney,30-12-2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63008,Yarraville,4/247 Williamstown Rd,3,t,NaN,S,Jas,30-12-2017,3013,Western Metropolitan,6543,6.3,Maribyrnong City Council
63009,Bayswater,62 Phyllis St,3,h,736000.0,SP,Biggin,31-03-2018,3153,Eastern Metropolitan,5030,23.2,Knox City Council
63010,Burwood,29 Summit Rd,4,h,NaN,PN,@Realty,31-03-2018,3125,Southern Metropolitan,5678,10.4,Monash City Council
63011,Doveton,12 Scarlet Dr,3,h,595000.0,PI,REMAX,31-03-2018,3177,South-Eastern Metropolitan,3533,28.8,Casey City Council
63012,Frankston,5/33 Dandenong East Rd,2,u,375000.0,SP,Aquire,31-03-2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63013,Frankston,7 Ince Ct,5,h,710000.0,PI,hockingstuart,31-03-2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63014,Frankston,1/34 Petrie St,2,u,345000.0,SP,Aquire,31-03-2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63015,Frankston,3/34 Petrie St,2,u,340000.0,SP,Aquire,31-03-2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63016,Frankston,4/34 Petrie St,2,u,347700.0,SP,Aquire,31-03-2018,3199,South-Eastern Metropolitan,17055,38.0,Frankston City Council
63017,Preston,229 Murray Rd,3,h,808000.0,S,RW,31-03-2018,3072,Northern Metropolitan,14577,8.4,Darebin City Council
63018,Roxburgh Park,3 Carr Pl,3,h,566000.0,S,Raine,31-03-2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63019,Roxburgh Park,9 Parker Ct,3,h,500000.0,S,Raine,31-03-2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63020,Roxburgh Park,5 Parkinson Wy,3,h,545000.0,S,Raine,31-03-2018,3064,Northern Metropolitan,5833,20.6,Hume City Council
63021,Thomastown,3/1 Travers St,3,u,NaN,PI,Barry,31-03-2018,3074,Northern Metropolitan,7955,15.3,Whittlesea City Council
63022,Williams Landing,1 Diadem Wy,4,h,NaN,SP,Aussie,31-03-2018,3027,Western Metropolitan,1999,17.6,Wyndham City Council

In [13]:
inputs_n=df.drop(['Suburb','Address','Type','Method','SellerG','Date','Regionname','CouncilArea'],axis='columns')
inputs_n

       Rooms      Price  Postcode  Propertycount  Distance
0          3  1490000.0      3067           4019       3.0
1          3  1490000.0      3067           4019       3.0
2          3  1420000.0      3067           4019       3.0
3          3  1515000.0      3040           1543       7.5
4          2   670000.0      3042           3464      10.4
5          2   530000.0      3042           3464      10.4
6          2   540000.0      3042           3464      10.4
7          3   715000.0      3042           3464      10.4
8          6        NaN      3021           1899      14.0
9          3  1925000.0      3206           3280       3.0
10         3   515000.0      3020           2185      10.5
11         4   717000.0      3020           2185      10.5
12         2  1675000.0      3078           2211       5.7
13         4  2008000.0      3078           2211       5.7
14         2   860000.0      3018           5301      11.0
15         4        NaN      3028           7630      15.5
16         3   720000.0      3025           5132       9.4
17         2   836000.0      3143           4836       6.3
18         2  2110000.0      3143           4836       6.3
19         3  1386000.0      3143           4836       6.3
20         2   580000.0      3143           4836       6.3
21         1   355000.0      3143           4836       6.3
22         3  1123100.0      3032           6567       4.3
23         3  1270000.0      3147           3052      10.2
24         4        NaN      3147           3052      10.2
25         3  1610000.0      3147           3052      10.2
26         4  1435000.0      3147           2894      10.2
27         4  1431000.0      3195           2824      21.5
28         4   996000.0      3195           2243      21.5
29         4        NaN      3049           1130      16.5
...      ...        ...       ...            ...       ...
62993      2  1000000.0      3181           4380       4.6
62994      3   640000.0      3750           2940      25.5
62995      4   520600.0      3750           2940      25.5
62996      3        NaN      3115           1328      25.2
62997      3   410000.0      3024           5262      27.2
62998      3   400000.0      3024           5262      27.2
62999      5        NaN      3024           5262      27.2
63000      3   416000.0      3024           5262      27.2
63001      3        NaN      3024           5262      27.2
63002      3   745000.0      3085           1369      12.7
63003      3   655000.0      3085           1369      12.7
63004      2   870000.0      3013           6543       6.3
63005      2   495000.0      3013           6543       6.3
63006      3  1000000.0      3013           6543       6.3
63007      2   410000.0      3013           6543       6.3
63008      3        NaN      3013           6543       6.3
63009      3   736000.0      3153           5030      23.2
63010      4        NaN      3125           5678      10.4
63011      3   595000.0      3177           3533      28.8
63012      2   375000.0      3199          17055      38.0
63013      5   710000.0      3199          17055      38.0
63014      2   345000.0      3199          17055      38.0
63015      2   340000.0      3199          17055      38.0
63016      2   347700.0      3199          17055      38.0
63017      3   808000.0      3072          14577       8.4
63018      3   566000.0      3064           5833      20.6
63019      3   500000.0      3064           5833      20.6
63020      3   545000.0      3064           5833      20.6
63021      3        NaN      3074           7955      15.3
63022      4        NaN      3027           1999      17.6

[63023 rows x 5 columns]

In [14]:
inputs_n.head()

   Rooms      Price  Postcode  Propertycount  Distance
0      3  1490000.0      3067           4019       3.0
1      3  1490000.0      3067           4019       3.0
2      3  1420000.0      3067           4019       3.0
3      3  1515000.0      3040           1543       7.5
4      2   670000.0      3042           3464      10.4

In [ ]:
sb.boxplot(x='Rooms',y='Price',data=df)

In [1]:
sb.paiplot(df,hue='Rooms',palette='his')

Populating the interactive namespace from numpy and matplotlib